CUDA_VISIBLE_DEVICES=0 python ../train.py \
 --checkname ft \
 --network searched_dense \
 --batch-size 16 \
 --workers 16 \
 --dataset cityscapes \
 --use-amp True \
 --opt-level O1 \
 --use-balanced-weights \
 --epoch 100 \
 --lr 0.01 \
 --nesterov \
 --gpu-ids 0 \
 --saved-arch-path ../searched_arch/ \
 --ft
