CUDA_VISIBLE_DEVICES=0 python ../search_layer.py \
 --checkname layer_search \
 --network path_dense_supernet \
 --F 20 \
 --joint True \
 --batch-size 2 \
 --workers 2 \
 --dataset cityscapes \
 --alpha-epoch 100 \
 --epoch 120 \
 --lr 0.025 \
 --min-lr 0.001 \
 --arch-lr 1e-3 \
 --weight-decay 3e-4 \
 --arch-weight-decay 3e-3
