CUDA_VISIBLE_DEVICES=0,1,2,3 python ../train.py \
 --checkname autodeeplab-baseline \
 --network autodeeplab-baseline \
 --dataset cityscapes \
 --batch-size 16 \
 --workers 4 \
 --epoch 2150 \
 --use-balanced-weights \
 --use-amp True \
 --opt-level O1 \
 --lr 0.05 \
 --nesterov \
 --gpu-ids 0,1,2,3 \
 --saved-arch-path ../searched_arch
