CUDA_VISIBLE_DEVICES=0 python ../train.py \
--checkname searched_dense \
--network searched_dense \
--batch-size 16 \
--workers 16 \
--dataset cityscapes \
--use-amp \
--opt-level O1 \
--use-balanced-weights \
--epoch 2150 \
--lr 0.05 \
--nesterov \
--gpu-ids 0 \
--saved-arch-path ../searched_arch/
